Theoretical Questions:

In [37]:
#1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it enhance Python's capabilities for numerical operations?
#Answer:
#NumPy is the fundamental package for numerical computations in Python, offering support for arrays, matrices, and an extensive collection of high-level mathematical functions.
#Advantages of NumPy

#Performance: NumPy’s array operations are executed at compiled C speed, making them significantly faster than equivalent operations performed using Python lists. 
#This performance boost is vital for handling large datasets and complex computations efficiently.

#Memory Efficiency: NumPy arrays use contiguous memory blocks, reducing overhead compared to Python lists. 
#This memory efficiency is essential when dealing with extensive datasets and enables faster data access and manipulation.

#Extensive Mathematical Functions: NumPy provides a rich collection of mathematical functions, making it an indispensable tool for scientific computing, linear algebra, statistics, and more. 
#These functions streamline complex calculations and data transformations.

#Interoperability: NumPy integrates with other libraries and tools in the scientific Python ecosystem, such as SciPy, Pandas, Matplotlib, and scikit-learn. 
#This integration allows for a comprehensive data analysis, visualization, and machine learning suite.

#NumPy is an indispensable tool for scientific computing, data analysis, and numerical computations in Python. 
#Its ability to efficiently handle arrays, perform complex mathematical operations, and seamlessly integrate with other libraries solidifies its position as the cornerstone of numerical computing in Python.

#NumPy’s capability to handle extensive datasets, execute complex mathematical operations, and integrate with various scientific computing tools, 
#makes it an indispensable asset for researchers, data scientists, engineers, and analysts working on numerical computations and data analysis tasks.

#NumPy’s array operations, mathematical functions, memory efficiency, and interoperability make it a foundational library in the Python ecosystem,
#empowering users to explore, analyze, and derive insights from data seamlessly and efficiently.

In [38]:
#2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the other?
#Answer:
#'Mean' & 'Average' are not the same thing. 
#They are frequently used interchangeably, but they should not even be. 
#The np.mean() method returns the arithmetic mean,
#but the np.average() function returns the algebraic mean if no additional parameters are specified, 
#but it may also be used to compute a weighted average.
#The term "mean" often refers to the "arithmetic mean", which is the sum of a set of numbers divided by the total number of the numbers in the set.
#The term "average" refers to a variety of computations, the "arithmetic mean" is one of them. Other terms include 'median,' 'mode,' 'weighted mean,' 'interquartile mean,' and a variety of others.

#Syntax of np.mean():
       # numpy.mean(a, axis=None, dtype=None, **kwargs)

#Syntax of np.average():
      # numpy.average(a, axis=None, weights=None, **kwargs)


#np.mean() accepts a few arguments that np.average() does not. 
#One of the most important is the dtype argument, which allows you to specify the data type that will be employed in the computation. 

#The algebraic mean of a NumPy array may be calculated using the numpy.mean() or numpy.average() functions.
#To compute the weighted algebraic mean, we may use numpy.average().
#We may utilize the dtype argument of the numpy.mean() method to compute the precise value of arithmetic mean.
#numpy.average() ignores boolean masks and computes the average across the full set of data. 
#While the numpy.mean() function takes boolean masks into consideration, compute the mean only over unmasked data.


In [39]:
#3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D arrays.
#Answer:
# the reverse of a NumPy array indicates changing the order. The first element will become the last element, the second last, the last the first, and so on. There are several methods for reversing a numpy array.
#Some of the most frequent methods for reversing a numpy array are as follows:

#Utilizing the len() with Loops
#Using the list slicing technique
#Using the flip() function
#Using the reverse() function

#example:Utilizing the len() with Loops

def reverse(nums):
    start_index = 0
    end_index = len(nums)-1
    while end_index > start_index:
        nums[start_index],nums[end_index] = nums[end_index],nums[start_index]
        start_index = start_index + 1
        end_index = end_index -1

n = [1,2,3,4,5,6,7,8,9,0]
reverse(n)
print(n)

[0, 9, 8, 7, 6, 5, 4, 3, 2, 1]


In [40]:
#Using the list slicing technique

import numpy as np
arr = np.array([2, 5, 1, 6, 7, 2, 4])
reve_arr = arr[::-1]
print(reve_arr)

[4 2 7 6 1 5 2]


In [41]:
#Using the flip() function

import numpy as np
arr = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
reversed_arr = np.flip(arr)
print('Reversed Array: ')
print(reversed_arr)

Reversed Array: 
[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


In [42]:
#Using the reverse() function

import array

arr=array.array('i',[1,2,6,8,4,2])
print(arr)
arr.reverse()
print("Reversed Array:",arr)

array('i', [1, 2, 6, 8, 4, 2])
Reversed Array: array('i', [2, 4, 8, 6, 2, 1])


In [43]:
#4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types in memory management and performance.
#Answer:
#The data type used in the array is specified through the dtype attribute assigned to the array. 
#These can include integers, strings, floating-point numbers and so on.
#You can check the type of data present in the NumPy array using the ‘.dtype’ attribute. 
#The data type of array ‘arr’ is ‘int’ (integer). Here, ‘32’ is related to memory allocation.

#Choosing the appropriate data type is essential to ensure efficient memory usage and accurate numerical calculations in NumPy. 
#By understanding the characteristics of different data types, users can optimize their code for performance and precision.

#Memory Efficiency
#Size of Data Types: Different data types occupy different amounts of memory. Choosing the right data type minimizes memory usage.
#Arrays vs. Lists: NumPy arrays are more memory-efficient than Python lists because they store elements of the same type in a contiguous block of memory. 
#This reduces overhead and improves cache performance.

#Performance Optimization
#Speed of Operations: Operations on NumPy arrays are generally faster than those on Python lists due to lower-level optimizations. 
#NumPy can leverage vectorized operations, which are significantly more efficient than Python loops.
#Broadcasting: NumPy allows broadcasting operations between arrays of different shapes, but the efficiency of these operations is influenced by the data types involved.
#Using compatible data types can enhance performance.

#Understanding and selecting the appropriate data types in NumPy is vital for optimizing memory management and performance. 
#By being mindful of the trade-offs between precision, memory usage, and computational speed, you can create more efficient and effective numerical applications.

In [44]:
#5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?
#Answer:
#Homogeneous Data Types:
#ndarrays require all elements to be of the same data type, which can be specified during array creation (e.g., int, float, bool).
#This uniformity allows for optimized storage and faster computation compared to lists, which can hold mixed data types.

#Multidimensional:
#ndarrays can represent arrays of any number of dimensions (1D, 2D, 3D, etc.), 
#enabling the manipulation of complex datasets (e.g., matrices, tensors).
#You can easily create and manipulate multi-dimensional arrays with a simple syntax.

#Contiguous Memory Storage:
#Data in an ndarray is stored in contiguous blocks of memory, 
#leading to better cache performance and more efficient access compared to lists, which store references to their elements.

#Vectorized Operations:
#ndarrays support vectorized operations, allowing you to perform element-wise operations without explicit loops. 
#This leads to concise code and improved performance.
#NumPy leverages underlying C and Fortran libraries for these operations, 
#making them significantly faster than equivalent operations performed with Python loops.

#Advanced Indexing and Slicing:
#ndarrays support advanced indexing and slicing capabilities, allowing you to select and manipulate subsets of data easily.
#You can use boolean indexing, fancy indexing, and multidimensional slicing to access elements in a flexible way.

#Broadcasting:
#Broadcasting allows you to perform operations on arrays of different shapes by automatically expanding the smaller array to match the shape of the larger array.
#This feature is particularly useful for performing arithmetic operations on arrays without needing to reshape them explicitly.

#Mathematical Functions:
#NumPy provides a wide range of mathematical functions that operate on ndarrays, 
#including statistical functions, linear algebra operations, and Fourier transforms.
#These functions are optimized for performance and can handle operations over entire arrays efficiently.

#Data Manipulation:
#ndarrays offer various methods for reshaping, stacking, splitting, and combining arrays, providing powerful tools for data manipulation.

#Differences Between ndarrays and Python Lists
#NumPy ndarrays are optimized for numerical computations with homogeneous data types and support for advanced features 
#like vectorization, broadcasting, and efficient memory management.
#Python lists are more flexible in terms of data types and can store mixed types but are less efficient for numerical operations, especially with large datasets.


In [45]:
#6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.
#Answer:
#1. Contiguous Memory Allocation
#Memory Efficiency: NumPy arrays store data in contiguous memory locations, 
#which allows for better cache performance and reduced memory fragmentation. 
#This contrasts with Python lists, which store references to objects in non-contiguous memory.
#Reduced Overhead: The contiguous storage leads to lower overhead in accessing elements compared to lists, 
#where each element is a separate object that may be scattered in memory.

#2. Homogeneous Data Types
#Type Uniformity: NumPy arrays are homogeneous, meaning all elements are of the same data type.
#This allows NumPy to optimize memory usage and computational speed, 
#as the system does not need to check data types during operations, unlike Python lists that can hold mixed types.
#Faster Operations: Since NumPy knows the data type of all elements, 
#it can execute operations in compiled code (using C or Fortran), 
#leading to faster execution compared to Python lists, where operations are interpreted and can vary in speed due to type checks.

#3. Vectorization
#Element-Wise Operations: NumPy allows for vectorized operations, 
#which enable you to perform operations on entire arrays without the need for explicit loops.
#This reduces the number of iterations in Python, significantly speeding up calculations.
#Batch Processing: Vectorization allows NumPy to take advantage of low-level optimizations and multi-threading capabilities, 
#resulting in performance gains for large datasets.

#The performance benefits of NumPy arrays over Python lists for large-scale numerical operations stem from their 
#contiguous memory allocation,type uniformity, vectorization, broadcasting, and optimized mathematical functions. 
#These features make NumPy not only faster but also more efficient in terms of memory usage,
#making it the preferred choice for numerical computations and data analysis in Python. 
#As a result, tasks that would be computationally expensive and 
#slow with Python lists can be executed quickly and efficiently with NumPy arrays, 
#allowing for scalable solutions in scientific computing, data science, and machine learning.


In [46]:
#7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and output.
#Answer:
#In NumPy, vstack() and hstack() are functions used to stack arrays vertically and horizontally, respectively. 
#vstack()
#Function: numpy.vstack(tup)
#Description: Stacks arrays in sequence vertically (row-wise). The input arrays must have the same shape along all but the first axis.
#Usage: Commonly used when you want to add new rows to an existing array.


#hstack()
#Function: numpy.hstack(tup)
#Description: Stacks arrays in sequence horizontally (column-wise). The input arrays must have the same shape along all but the second axis.
#Usage: Commonly used when you want to add new columns to an existing array.

#Example of vstack():
import numpy as np

# Create two 2D arrays
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])

# Stack the arrays vertically
result_vstack = np.vstack((array1, array2))

print("Result of vstack:")
print(result_vstack)

Result of vstack:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [48]:
#Example of hstack()
import numpy as np

# Create two 2D arrays
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7], [8]])

# Stack the arrays horizontally
result_hstack = np.hstack((array1, array2))

print("Result of hstack:")
print(result_hstack)

Result of hstack:
[[1 2 3 7]
 [4 5 6 8]]


In [49]:
#8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various array dimensions.
#Answer:
#fliplr():
#Function: numpy.fliplr(m)
#Description: Flips an array from left to right. This means that the columns of the array are reversed, but the rows remain unchanged.
#Usage: It is primarily used for 2D arrays (matrices),
#but it can also be applied to higher-dimensional arrays by treating the last two axes as rows and columns.


#flipud():
#Function: numpy.flipud(m)
#Description: Flips an array upside down. This means that the rows of the array are reversed, but the columns remain unchanged.
#Usage: Like fliplr(), it is primarily used for 2D arrays 
#but can be applied to higher-dimensional arrays by treating the first two axes as rows and columns.

#Effects on Various Array Dimensions:
#2D Arrays (Matrices):
#fliplr(): Reverses columns, resulting in the last column becoming the first and the first column becoming the last.
#flipud(): Reverses rows, making the last row the first and the first row the last.

#1D Arrays:
#Both Methods: fliplr() and flipud() have the same effect on 1D arrays, as they will both reverse the order of the elements.

#Higher-Dimensional Arrays:
#Both functions will still apply to the last two axes of the array, treating them as the rows and columns.

#Example of fliplr():
import numpy as np

# Create a 2D array (matrix)
array_2d = np.array([[1, 2, 3],
                     [4, 5, 6]])

# Flip the array left to right
result_fliplr = np.fliplr(array_2d)

print("Original Array:")
print(array_2d)
print("\nResult of fliplr:")
print(result_fliplr)

Original Array:
[[1 2 3]
 [4 5 6]]

Result of fliplr:
[[3 2 1]
 [6 5 4]]


In [50]:
#Example of flipud():
import numpy as np

# Create a 2D array (matrix)
array_2d = np.array([[1, 2, 3],
                     [4, 5, 6]])

# Flip the array upside down
result_flipud = np.flipud(array_2d)

print("Original Array:")
print(array_2d)
print("\nResult of flipud:")
print(result_flipud)

Original Array:
[[1 2 3]
 [4 5 6]]

Result of flipud:
[[4 5 6]
 [1 2 3]]


In [52]:
#9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?
#Answer:
#he array_split() method in NumPy is used to split an array into multiple sub-arrays along a specified axis. 
#It provides a way to divide an array into sections, which can be useful for various data processing tasks.

#Functionality of array_split():
#Function Signature: numpy.array_split(ary, indices_or_sections, axis=0)

#Parameters:
#ary: The input array that you want to split.

#indices_or_sections: This can be an integer or an array of indices:
#If an integer, it specifies the number of equal-sized sub-arrays to create.
#If an array of indices, it specifies the exact indices at which to split the array.

#axis: The axis along which to split the array. The default is 0 (vertical split).

#Return Value:
#Returns a list of sub-arrays.
#Handling Uneven Splits
#When the size of the array is not perfectly divisible by the number of sections specified, 
#array_split() will handle the splits by distributing the elements as evenly as possible:

#The method attempts to create sub-arrays of nearly equal size. 
#If there are any remainder elements after dividing, they will be distributed one by one to the first few sub-arrays.
#This means that the first few sub-arrays may contain one more element than the others.

#Example of array_split():
import numpy as np

# Create a 1D array
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Split the array into 3 equal parts
split_array = np.array_split(array, 3)

print("Split into 3 parts:")
for i, sub_array in enumerate(split_array):
    print(f"Sub-array {i}: {sub_array}")

Split into 3 parts:
Sub-array 0: [1 2 3]
Sub-array 1: [4 5 6]
Sub-array 2: [7 8 9]


In [53]:
#Handling Uneven Splits:

# Split the same array into 4 parts
split_array_uneven = np.array_split(array, 4)

print("\nSplit into 4 parts (uneven):")
for i, sub_array in enumerate(split_array_uneven):
    print(f"Sub-array {i}: {sub_array}")


Split into 4 parts (uneven):
Sub-array 0: [1 2 3]
Sub-array 1: [4 5]
Sub-array 2: [6 7]
Sub-array 3: [8 9]


In [55]:
#10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array operations?
#Answer:
#Vectorization:
#Vectorization refers to the ability to apply operations to entire arrays or 
#large datasets in a single step without the need for explicit loops. 
#In NumPy, this is achieved by using operations that are optimized and implemented in lower-level languages (such as C or Fortran), 
#allowing for faster execution.

#Broadcasting:
#Broadcasting is a powerful mechanism that allows NumPy to perform arithmetic operations on arrays of different shapes and sizes.
#It automatically expands the smaller array across the larger array's dimensions without copying data,
#thus enabling element-wise operations even when the dimensions do not match.

#Contribution to Efficient Array Operations:
#Performance Gains:
#Both vectorization and broadcasting eliminate the need for explicit loops in Python, 
#which are generally slower due to the interpreted nature of Python. 
#This leads to a significant speedup in array operations, especially for large datasets.

#Memory Efficiency:
#Broadcasting reduces memory consumption by avoiding unnecessary copies of data. 
#Instead of creating full-size arrays, NumPy efficiently applies operations to the existing arrays without using extra memory.

#Concise and Readable Code:
#These concepts allow for more expressive and clear code, 
#making it easier to implement complex operations in fewer lines. This can lead to quicker development and fewer bugs.

#Parallel Processing:
#Under the hood, vectorized operations and broadcasting can leverage optimized libraries (like BLAS and LAPACK) 
#that may utilize multi-threading and other low-level optimizations, further enhancing performance.


#Example of Vectorization:
import numpy as np

# Create a NumPy array
array = np.array([1, 2, 3, 4, 5])

# Vectorized operation: adding 10 to each element
result = array + 10

print("Original array:", array)
print("Result after vectorization:", result)

Original array: [1 2 3 4 5]
Result after vectorization: [11 12 13 14 15]


In [56]:
#Example of Broadcasting:
import numpy as np

# Create a 1D array and a 2D array
array_1d = np.array([1, 2, 3])
array_2d = np.array([[10], [20], [30]])

# Broadcasting: Adding a 1D array to a 2D array
result_broadcasting = array_2d + array_1d

print("2D Array:\n", array_2d)
print("1D Array:\n", array_1d)
print("Result after broadcasting:\n", result_broadcasting)

2D Array:
 [[10]
 [20]
 [30]]
1D Array:
 [1 2 3]
Result after broadcasting:
 [[11 12 13]
 [21 22 23]
 [31 32 33]]


Practical Questions:

In [3]:
#1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

import numpy as np

arr = np.random.randint(1,100, (3,3))

In [4]:
arr

array([[27, 70, 95],
       [58,  1, 76],
       [49, 92, 21]])

In [5]:
arr.T             # T refers to tanspose which is used to interchange rows and columns

array([[27, 58, 49],
       [70,  1, 92],
       [95, 76, 21]])

In [10]:
#2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

arr1D = np.arange(10)
arr1D

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
arr1D.reshape(2,5)                  #reshape into 2x5

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [12]:
arr1D.reshape(5,2)                  ##reshape into 5x2

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [13]:
#3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

arr2D = np.random.rand(4,4)
arr2D

array([[0.51329299, 0.09900609, 0.54010576, 0.84725695],
       [0.16133308, 0.75161924, 0.79773497, 0.4257856 ],
       [0.29898699, 0.5644327 , 0.77056822, 0.38957069],
       [0.01172291, 0.79332696, 0.94853778, 0.38940608]])

In [14]:
arr = np.pad(arr2D, pad_width=1, mode='constant', constant_values=0)
arr

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.51329299, 0.09900609, 0.54010576, 0.84725695,
        0.        ],
       [0.        , 0.16133308, 0.75161924, 0.79773497, 0.4257856 ,
        0.        ],
       [0.        , 0.29898699, 0.5644327 , 0.77056822, 0.38957069,
        0.        ],
       [0.        , 0.01172291, 0.79332696, 0.94853778, 0.38940608,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ]])

In [15]:
#4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.

arr = np.arange(10,60,5)
arr

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55])

In [16]:
#5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element.

arr_of_strings = ['python', 'numpy', 'pandas']
arr_of_strings

['python', 'numpy', 'pandas']

In [17]:
np.char.upper(arr_of_strings)                 #upper case

array(['PYTHON', 'NUMPY', 'PANDAS'], dtype='<U6')

In [18]:
np.char.lower(arr_of_strings)             #lower case

array(['python', 'numpy', 'pandas'], dtype='<U6')

In [19]:
np.char.title(arr_of_strings)              #title case

array(['Python', 'Numpy', 'Pandas'], dtype='<U6')

In [21]:
#6. Generate a NumPy array of words. Insert a space between each character of every word in the array.

arr = np.array(['python', 'numpy', 'pandas'])
arr


array(['python', 'numpy', 'pandas'], dtype='<U6')

In [22]:
arr = np.char.join(' ', arr)
arr

array(['p y t h o n', 'n u m p y', 'p a n d a s'], dtype='<U11')

In [24]:
#7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

arr = np.random.randint(1,10, (3,3))
arr

array([[6, 2, 7],
       [8, 1, 5],
       [2, 3, 1]])

In [25]:
addition = arr + 5                     #addition
addition

array([[11,  7, 12],
       [13,  6, 10],
       [ 7,  8,  6]])

In [26]:
subtraction = arr - 2                   #subtraction
subtraction

array([[ 4,  0,  5],
       [ 6, -1,  3],
       [ 0,  1, -1]])

In [27]:
multiplication = arr * 3                 #multiplication
multiplication

array([[18,  6, 21],
       [24,  3, 15],
       [ 6,  9,  3]])

In [28]:
division = arr / 4                      #division
division

array([[1.5 , 0.5 , 1.75],
       [2.  , 0.25, 1.25],
       [0.5 , 0.75, 0.25]])

In [29]:
#8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

identity_matrix = np.eye(5,5,dtype=int)
identity_matrix

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [30]:
np.diagonal(identity_matrix, offset=0, axis1=0, axis2=1)

array([1, 1, 1, 1, 1])

In [31]:
#9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.


arr = np.random.randint(0,1000,100)
arr

array([688, 866, 943, 342, 172, 760, 547,  72,   5, 697, 510, 915, 992,
       680, 746, 265, 767, 331,  67, 526, 556, 381, 809, 851, 421, 297,
       465, 216, 320, 367, 307, 620, 298,  45, 397,  49, 865, 702, 758,
       267, 579,  31, 155, 122, 537, 503, 997, 817, 364,  73, 266, 107,
       333, 923, 939, 986, 303, 480, 634, 998, 494, 248, 649,  21, 363,
       269, 663, 484, 568, 421,   2, 204, 903, 502, 734, 507, 630, 375,
       989, 181, 884, 317, 324, 471, 271, 155, 181, 324, 638, 139, 301,
       617, 228, 781,  50, 657,  78, 785, 113, 440])

In [33]:
def prime(arr):
    prime_list = []
    for i in arr:
        if i == 0 or i == 1:
            continue
        else:
            for j in range(2, int(i/2)+1):
                if i % j == 0:
                    break
            else:
                prime_list.append(i)
    return prime_list

prime(arr)

[547,
 5,
 331,
 67,
 809,
 421,
 367,
 307,
 397,
 31,
 503,
 997,
 73,
 107,
 269,
 421,
 2,
 181,
 317,
 271,
 181,
 139,
 617,
 113]

In [34]:
#10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.

temp_of_month = np.random.randint(10,40,30)
temp_of_month

array([31, 16, 20, 11, 24, 19, 36, 11, 14, 30, 10, 14, 14, 14, 26, 18, 24,
       13, 33, 13, 29, 38, 33, 31, 23, 10, 28, 33, 13, 31])

In [35]:
np.mean(temp_of_month)

22.0